server:
  port: 8443
  ssl:
      key-store: ./src/main/resources/keystore.p12
      key-store-password: 12345678
      keyStoreType: PKCS12
      keyAlias: tomcat
      
spring:
  data:
    mongodb:
      database: users


  
